export default {
  WHITE_SOLDIER: "WHITE_SOLDIER",
  WHITE_ROOK: "WHITE_ROOK",
  WHITE_KNIGHT: "WHITE_KNIGHT",
  WHITE_BISHOP: "WHITE_BISHOP",
  WHITE_QUEEN: "WHITE_QUEEN",
  WHITE_KING: "WHITE_KING",
  BLACK_SOLDIER: "BLACK_SOLDIER",
  BLACK_ROOK: "BLACK_ROOK",
  BLACK_KNIGHT: "BLACK_KNIGHT",
  BLACK_BISHOP: "BLACK_BISHOP",
  BLACK_QUEEN: "BLACK_QUEEN",
  BLACK_KING: "BLACK_KING",
};
